### ISSUE TITLE
Conversion of the `main` entry to ESM breaks jest testcases

### ISSUE THREAD

**Issue by Carsten-Leue** [silverwind/is-cidr#8]
After the conversion of the `main` entry to ESM JS code that use a `require` statement on the module fails.

I suggest to sever the ES5 CJS implementation via the `main` entry and the `ESM` version via the `module` entry.

**Comment by silverwind** [comment]
It should work out of the box if your project is `type=module` in package.json and jest is configured in ESM mode:

https://jestjs.io/docs/ecmascript-modules

I'm using such jest config in multiple projects and it works fine with both ESM and CJS dependencies. Also see this sample config:

https://github.com/silverwind/updates/blob/master/jest.config.js

**Comment by Carsten-Leue** [comment]
Probably, but it breaks existing projects that are using the non-experimental ESM support in jest.

Also - to my best knowledge - an NPM module advertises its ESM version via the `module` entry point and the `main` entry point is reserved for CJS. 

So if your intent is to no longer support CJS, I suggest to only expose the `module` entry point, but ideally you'd provide a CJS version in addition to the ESM version (e.g. by transpiling the code).

This is the reference I have in mind https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md

**Comment by silverwind** [comment]
I don't indent to provide CJS (use v4 if you need it), but if adding `module` makes it more compatible, yes I can try that.

**Comment by silverwind** [comment]
So it appears `module` is a non-standard property only recognized by certain bundlers [like esbuild](https://esbuild.github.io/api/#main-fields) and it is not actually recognized by Node.js which needs either `main` or `exports` and `type=module` to correctly load ESM.

I'm not sure how to go ahead. Nowhere in the node docs, it says that `main` is only for CJS, but it appears some tools like jest in CJS mode might (wrongly) assume it because of this [2016 proposal](https://github.com/dherman/defense-of-dot-js/blob/f31319be735b21739756b87d551f6711bd7aa283/proposal.md) that was never implemented in Node.

**Comment by silverwind** [comment]
I think I'll replace `main` with `exports`, as [other authors](https://github.com/sindresorhus/meta/discussions/15) have done, it seems like the most compatible approach.
